package com.example.ui

object LanguageManager {
    private val pt = mapOf(
        "app_title" to "SinapseMed",
        "app_subtitle" to "Mente Médica: Resumos de Aulas & Estudo Acadêmico Dirigido por IA",
        "online" to "IA ACADÊMICA ONLINE",
        "offline" to "IA ACADÊMICA OFFLINE",
        "warning_title" to "Aviso Importante",
        "warning_text" to "A chave da API do Gemini (IA) não está configurada! Por favor, acesse o painel Secrets (Segredos) no painel esquerdo ou configurações do AI Studio e insira uma GEMINI_API_KEY válida para ativar a inteligência acadêmica e analisar seus arquivos de aula, livros universitários e anotações.",
        "upload_btn" to "Enviar Material de Estudos",
        "upload_sub" to "Selecione resumos de aulas, livros ou slides para estudar",
        "recent_docs" to "Seus Materiais de Estudo",
        "empty_docs" to "Nenhum material de estudo carregado",
        "empty_docs_sub" to "Faça upload do seu primeiro PDF de aula ou caderno para a IA ler, resumir, criar áudio-aulas explicativas, slides didáticos e questionários de simulado inteligente com casos clínicos de prova!",
        "pages_label" to "página(s)",
        "back" to "Voltar",
        "clear_chat" to "Reiniciar Chat",
        "pdf_pages" to "PÁGINAS REAIS DA AULA (TOQUE PARA VER):",
        "ai_summary" to "Resumo Acadêmico Inteligente",
        "chat_context" to "CONVERSA CONTEXTUAL DE ESTUDOS COM A IA:",
        "brain_connected" to "Material Conectado com Sucesso!",
        "chat_welcome_sub" to "Pergunte qualquer dúvida teórica, fisiopatológica ou conceitual da matéria. Responderei analisando os textos acadêmicos fornecidos.",
        "ask_placeholder" to "Pergunte sobre a matéria...",
        "ask_disabled" to "IA Acadêmica Offline...",
        "viewer_title" to "Visualização de Página",
        "close" to "Fechar",
        "thinking" to "Analisando fisiopatologia e bases teóricas...",
        "tab_chat" to "Estudo e Dúvidas 💬",
        "tab_quiz" to "Simulado de Questões 🧠",
        "tab_video" to "Slides e Vídeo Aula 🎥", 
        "quiz_title" to "Simulado Teórico Inteligente de Medicina",
        "quiz_subtitle" to "Responda questões baseadas na aula acadêmica. A IA o guiará dos conceitos fundamentais até o raciocínio fisiopatológico e diagnóstico crucial para provas universitárias.",
        "quiz_difficulty" to "Dificuldade atual:",
        "easy" to "Fácil (Fundamentos)",
        "medium" to "Médio (Fisiopatologia)",
        "hard" to "Difícil (Caso Clínico / Simulado)",
        "next_question" to "Próxima Pergunta",
        "quiz_congrats" to "Parabéns!",
        "quiz_congrats_desc" to "Você concluiu esta trilha teórica de estudos. Pronto para se desafiar no próximo nível?",
        "start_quiz_btn" to "Iniciar Simulado de Questões",
        "answer_feedback_correct" to "Resposta correta!",
        "answer_feedback_wrong" to "Resposta incorreta. A resposta correta era: ",
        "play_audio" to "Ouvir Explicação em Áudio 🔊",
        "pause_audio" to "Pausar Explicação ⏸️",
        "stop_audio" to "Parar Explicação ⏹️",
        "audio_active" to "Reproduzindo Explicação da IA...",
        "audio_paused" to "Explicação Pausada",
        "video_tab_title" to "Vídeo Aula Interativa por Slides com IA",
        "video_btn" to "Assistir Apresentação Assistida em Vídeo 🖥️",
        "video_active" to "Modo Aula Ativo (Apresentação Visual por Slides & Texto)",
        "video_slide" to "Slide",
        "study_level" to "Nível da sua Trilha Acadêmica:",
        "quiz_explanation_title" to "Estudo Dirigido e Resposta com IA:",
        "quiz_score" to "Desempenho no Simulado:",
        "next_level_desc" to "Avance para as perguntas de nível intermediário e avançado com casos clínicos integrados para aprimorar sua nota na faculdade!",
        "level_easy_completed" to "Nível FÁCIL concluído! Base e terminologias teóricas consolidadas.",
        "level_medium_completed" to "Nível MÉDIO concluído! Boa compreensão de caminhos fisiopatológicos e laboratoriais.",
        "level_hard_completed" to "Nível DIFÍCIL concluído! Excelente domínio teórico e diagnóstico acadêmico!",
        "quiz_finished" to "Parabéns por dominar toda a matéria teórica no SinapseMed!",
        "video_narrator" to "Preceptor / Tutor de IA:"
    )

    private val en = mapOf(
        "app_title" to "SinapseMed",
        "app_subtitle" to "Medical Mind: Class Summaries & AI Guided Academic Studies",
        "online" to "ACADEMIC AI ONLINE",
        "offline" to "ACADEMIC AI OFFLINE",
        "warning_title" to "Important Warning",
        "warning_text" to "The Gemini API Key is not configured! Please open the Secrets tab on the left panel or AI Studio settings, add a valid 'GEMINI_API_KEY' to enable the academic AI engine to analyze your class notes, textbooks, and folders.",
        "upload_btn" to "Upload Study Materials",
        "upload_sub" to "Select lecture slides, textbooks, or notes to study",
        "recent_docs" to "Your Academic Materials",
        "empty_docs" to "No study materials processed yet",
        "empty_docs_sub" to "Upload your first medical lecture PDF or notebook page to let the AI read, summarize, speak audio-lectures, design slides, and generate interactive university mock tests!",
        "pages_label" to "page(s)",
        "back" to "Back",
        "clear_chat" to "Reset Chat",
        "pdf_pages" to "REAL LECTURE PAGES (TAP TO VIEW):",
        "ai_summary" to "Smart Academic Summary",
        "chat_context" to "CONTEXTUAL ALUMNI STUDY DISCUSSION WITH THE AI:",
        "brain_connected" to "Material Linked Successfully!",
        "chat_welcome_sub" to "Ask any medical, anatomical, or pathophysiological questions about the lecture. I will search and answer based on your uploaded material.",
        "ask_placeholder" to "Ask about the subject...",
        "ask_disabled" to "Academic AI is Offline...",
        "viewer_title" to "Lecture Preview",
        "close" to "Close",
        "thinking" to "Analyzing pathophysiology and academic context...",
        "tab_chat" to "Study Chat 💬",
        "tab_quiz" to "Mock Test & Quiz 🧠",
        "tab_video" to "Slides & Class Voice 🎥",
        "quiz_title" to "Smart Academic Medical Quiz",
        "quiz_subtitle" to "Answer questions based on the class material. The AI will guide you from core definitions to complex disease tracks for college exam prep.",
        "quiz_difficulty" to "Current academic level:",
        "easy" to "Easy (Fundamentals)",
        "medium" to "Medium (Pathophysiology)",
        "hard" to "Hard (Clinical Practice Mock)",
        "next_question" to "Next Question",
        "quiz_congrats" to "Congratulations!",
        "quiz_congrats_desc" to "You completed this theoretical track. Ready to advance to the next level?",
        "start_quiz_btn" to "Start Smart Questions",
        "answer_feedback_correct" to "Correct answer!",
        "answer_feedback_wrong" to "Incorrect. The correct answer was: ",
        "play_audio" to "Listen to Audio Lecture 🔊",
        "pause_audio" to "Pause Audio ⏸️",
        "stop_audio" to "Stop Audio ⏹️",
        "audio_active" to "Playing Audio Class...",
        "audio_paused" to "Audio Paused",
        "video_tab_title" to "AI Interactive Slide Presentation",
        "video_btn" to "Watch Video Assisted Presentation 🖥️",
        "video_active" to "Class Mode Active (Visual Slide & Text Presentation)",
        "video_slide" to "Slide",
        "study_level" to "Your Academic Milestone:",
        "quiz_explanation_title" to "AI Academic Mentorship Explanation:",
        "quiz_score" to "Lecture Quiz Score:",
        "next_level_desc" to "Proceed to intermediate and advanced questions to perfect your medical exam scores!",
        "level_easy_completed" to "EASY level completed! Great medical vocabulary and concepts.",
        "level_medium_completed" to "MEDIUM level completed! Solid outline of pathophysiology and clinical findings.",
        "level_hard_completed" to "HARD level completed! Outstanding scholarly capability on this topic!",
        "quiz_finished" to "Congrats on mastering the entire academic subject on SinapseMed!",
        "video_narrator" to "AI College Preceptor:"
    )

    private val es = mapOf(
        "app_title" to "SinapseMed",
        "app_subtitle" to "Mente Médica: Resúmenes de Clases y Estudio Académico Dirigido por IA",
        "online" to "IA ACADÉMICA ONLINE",
        "offline" to "IA ACADÉMICA OFFLINE",
        "warning_title" to "Aviso Importante",
        "warning_text" to "¡La clave de API de Gemini no está configurada! Por favor, acceda a la pestaña 'Secrets' en el panel izquierdo o configuración de AI Studio y escriba una GEMINI_API_KEY válida para activar el tutor académico de IA e interactuar con sus PDFs de clase, libros y cuadernos.",
        "upload_btn" to "Subir Material de Estudio",
        "upload_sub" to "Seleccione apuntes de clase, libros o diapositivas para estudiar",
        "recent_docs" to "Tus Materiales de Estudio",
        "empty_docs" to "Ningún material de estudio cargado",
        "empty_docs_sub" to "¡Sube tu primera clase o PDF médico para que la IA lo analice, resuma, cree audioclases teóricas, diapositivas y exámenes simulados interactivos con casos clínicos de examen!",
        "pages_label" to "página(s)",
        "back" to "Volver",
        "clear_chat" to "Restablecer Chat",
        "pdf_pages" to "PÁGINAS REALES DE LA CLASE (TOCAR PARA VER):",
        "ai_summary" to "Resumen Académico Inteligente",
        "chat_context" to "CHARLA COOPERATIVA DE ESTUDIOS CON IA:",
        "brain_connected" to "¡Material Conectado con Éxito!",
        "chat_welcome_sub" to "Pregunte cualquier duda teórica, anatómica o fisiopatológica de la clase. Responderé analizando los textos académicos provistos.",
        "ask_placeholder" to "Preguntar sobre la materia...",
        "ask_disabled" to "IA Académica sin conexión...",
        "viewer_title" to "Vista de Clase",
        "close" to "Cerrar",
        "thinking" to "Analizando patología y bases teóricas...",
        "tab_chat" to "Estudio y Dudas 💬",
        "tab_quiz" to "Simulado de Preguntas 🧠",
        "tab_video" to "Slides y Video Clase 🎥",
        "quiz_title" to "Cuestionario Teórico Inteligente de Medicina",
        "quiz_subtitle" to "Responde preguntas basadas en la clase. La IA te guiará desde los conceptos básicos hasta el análisis fisiopatológico clave para exámenes de medicina.",
        "quiz_difficulty" to "Nivel académico:",
        "easy" to "Fácil (Módulos)",
        "medium" to "Medio (Fisiopatología)",
        "hard" to "Difícil (Casos Clínicos)",
        "next_question" to "Siguiente Pregunta",
        "quiz_congrats" to "¡Felicitaciones!",
        "quiz_congrats_desc" to "Has completado esta fase teórica de estudios. ¿Listo para dar el siguiente paso?",
        "start_quiz_btn" to "Iniciar Simulado de Preguntas",
        "answer_feedback_correct" to "¡Respuesta correcta!",
        "answer_feedback_wrong" to "Respuesta incorrecta. La respuesta correcta era: ",
        "play_audio" to "Escuchar Clase en Audio 🔊",
        "pause_audio" to "Pausar Audio ⏸️",
        "stop_audio" to "Detener Audio ⏹️",
        "audio_active" to "Reproduciendo Clase de Audio...",
        "audio_paused" to "Audio Pausado",
        "video_tab_title" to "Presentación de diapositivas interactiva por IA",
        "video_btn" to "Ver Clase por Video 🖥️",
        "video_active" to "Presentación Visual de Diapositivas con Voz de Tutor",
        "video_slide" to "Slide",
        "study_level" to "Nivel de tu Ruta Académica:",
        "quiz_explanation_title" to "Explicación del Tutor de IA:",
        "quiz_score" to "Desempeño en el Simulado:",
        "next_level_desc" to "¡Avanza a preguntas y casos clínicos del simulado para aumentar tus notas de la facultad!",
        "level_easy_completed" to "¡Nivel FÁCIL completado! Estupenda base teórica y terminologías.",
        "level_medium_completed" to "¡Nivel MEDIO completado! Buen entendimiento de fisiopatología y exámenes complementarios.",
        "level_hard_completed" to "¡Nivel DIFÍCIL completado! ¡Excelente dominio de resolución diagnóstica académica!",
        "quiz_finished" to "¡Felicitaciones por completar toda la materia académica del SinapseMed!",
        "video_narrator" to "Tutor de IA Universitaria:"
    )

    fun getString(key: String, lang: AppLanguage): String {
        val map = when (lang) {
            AppLanguage.EN -> en
            AppLanguage.ES -> es
            AppLanguage.PT -> pt
        }
        return map[key] ?: pt[key] ?: key
    }
}
